services:
  postgresql:
    image: postgres:17.2-bookworm
    container_name: pg
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456789
      POSTGRES_DB: postgres
    ports:
      - 5432:5432
    networks:
      - msg-network
    volumes:
      - ./init/init.sql:/docker-entrypoint-initdb.d/init.sql
      - pgdata:/var/lib/postgresql/datas

  web_server:
    container_name: web
    build:
      context: ./SimpleMessenger.Server
      dockerfile: Dockerfile
    restart: always
    ports:
      - 5000:5000
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5000
    networks:
      - msg-network
    depends_on:
      - postgresql
    volumes:
      - ./SimpleMessenger.Server/SimpleMessenger.WebServer/appsettings.json:/app/appsettings.json

  nginx:
    container_name: nginx
    build:
      context: ./SimpleMessenger.Clients
      dockerfile: Dockerfile
    ports:
      - 8080:80
    networks:
      - msg-network
    depends_on:
      - web_server

volumes:
  pgdata:

networks:
  msg-network:
    driver: bridge